### ISSUE TITLE
1.3.9 version sting missing in EthStats

### ISSUE THREAD

**Issue by MysticRyuujin** [NethermindEth/nethermind#1198]
Was fine in previous release?

Now:
`Nethermind/v-20191227/X64-Microsoft Windows 10.0.18363/Core3.0.0`

Then:
`Nethermind/v1.3.8+8a00acc/X64-Microsoft Windows 10.0.18363/Core3.0.0`

**Comment by tkstanczak** [comment]
@matilote - part of
1) make it one button / one script release
2) document it on Confluence
3) test after each release that downloads / version / file sizes are all right - do not automate the last part

**Comment by matilote** [comment]
Fixed with PR's #1200 #1202 
1. Implemented with _Build Commands_
2. done

**Comment by MysticRyuujin** [comment]
If this is the new and expected version string, cool, but, `1.4.0` is still not in my agent string:

`Nethermind/v-20191231/X64-Microsoft Windows 10.0.18363/Core3.0.0`

**Comment by matilote** [comment]
Will investigate tomorrow, must be specific to Windows as on Linux the version looks fine.
![image](https://user-images.githubusercontent.com/33068017/71626169-228a8100-2bec-11ea-8aa3-ee201eab279a.png)

**Comment by matilote** [comment]
@MysticRyuujin Could you please check if git-hash file is present in app's folder?
![image](https://user-images.githubusercontent.com/33068017/71626275-aba1b800-2bec-11ea-96c9-64d367c1031e.png)

**Comment by MysticRyuujin** [comment]
It's present and contains `1.4.0-1-g5a89e56e5`

**Comment by MysticRyuujin** [comment]
File exists in 1.4.1 zip also:
`1.4.1-0-g9ff231103`

`Nethermind/v-20191231/X64-Microsoft Windows 10.0.18363/Core3.0.0`

**Comment by tkstanczak** [comment]
@matilote can it be that the version file is in the warp directory?

**Comment by tkstanczak** [comment]
fixed in the latest commit - will be there for 1.4.3
