### ISSUE TITLE
Nethermind clients do not mine in private aura network

### ISSUE THREAD

**Issue by moritz-mbw** [NethermindEth/nethermind#1536]
**Setup:** 
Private Aura network
Ubuntu 18.04 (WSL1)
1 Parity client (parity/parity:v2.7.2-stable via docker)
2 Nethermind clients (nethermind/nethermind:1.6.25-arm64 via docker)

**Procedure:**
All 3 nodes are started. They successfully connect to each other.
All 3 nodes are listed as validators in the genesis file.
Sending multiple (like 20) simple value transactions to be mined.

**Expected behavior:**
Transactions should be mined to blocks.
Some blocks should be mined by the nethermind clients.

**Actual behavior:**
All blocks are mined by the parity client.
Nethermind clients communicate following debug message (extract):

Nethermind client 1:
```2020-03-13 09:48:05.0079|DEBUG|Consensus.AuRa.AuRaSealer|Skip seal block 4: 0x45dbc38c09eab8d1553667fe9d1bc4074450c7b3 is not proposer of AuRa step 1584092885.

2020-03-13 09:48:05.0108|DEBUG|Blockchain.Producers.BaseBlockProducer|Waiting 00:00:00.9900000 for next AuRa step.
2020-03-13 09:48:05.4918|DEBUG|Network.Discovery.NodesLocator|Finished discovery cycle, tried contacting 0 nodes. All nodes count before the process: 0, after the process: 0
2020-03-13 09:48:05.5106|DEBUG|Network.Discovery.NodesLocator|Starting discovery process for node: masterNode: 0x38e72eeffc7be91834f7f16b7375b1978babf531eeeef5df74bba14bcf20d3b120935d07b1aae9785feaa2f8a7b849a8155b036eaeb03069ad015e7b9f30eb93
2020-03-13 09:48:05.7410|DEBUG|Blockchain.Synchronization.Synchronizer|Allocating block sync.
2020-03-13 09:48:06.0154|DEBUG|Consensus.AuRa.AuRaSealer|Skip seal block 4: 0x45dbc38c09eab8d1553667fe9d1bc4074450c7b3 is not proposer of AuRa step 1584092886.

2020-03-13 09:48:06.0165|DEBUG|Blockchain.Producers.BaseBlockProducer|Waiting 00:00:00.9840000 for next AuRa step.
2020-03-13 09:48:06.6530|DEBUG|Network.Discovery.NodesLocator|Finished discovery cycle, tried contacting 0 nodes. All nodes count before the process: 0, after the process: 0
2020-03-13 09:48:06.6696|DEBUG|Network.Discovery.NodesLocator|Starting discovery process for node: randomNode: 0ccda3...a0307a
2020-03-13 09:48:06.7431|DEBUG|Blockchain.Synchronization.Synchronizer|Allocating block sync.
2020-03-13 09:48:07.0088|DEBUG|Consensus.AuRa.AuRaSealer|Skip seal block 4: 0x45dbc38c09eab8d1553667fe9d1bc4074450c7b3 is not proposer of AuRa step 1584092887.

2020-03-13 09:48:07.0132|DEBUG|Blockchain.Producers.BaseBlockProducer|Waiting 00:00:00.9880000 for next AuRa step.
2020-03-13 09:48:07.2552|INFO|Blockchain.Synchronization.SyncServer|Discovered a new block         4 09:48:07 (0xaa34c8...a32bbd), tx count: 3 sealed by 0x00bd138abd70e2f00903268f3db08f2d25677c9e, sent by 10.5.0.2:30300
2020-03-13 09:48:07.6555|DEBUG|Consensus.AuRa.AuRaBlockFinalizationManager|Blocks finalized by 4 (0xaa34c8294e424c0fd51aef9e4ebed51b8a1ce893044d95e4cdc413bd90a32bbd): 4 (0xaa34c8294e424c0fd51aef9e4ebed51b8a1ce893044d95e4cdc413bd90a32bbd).
2020-03-13 09:48:07.7470|DEBUG|Blockchain.Synchronization.Synchronizer|Allocating block sync.
2020-03-13 09:48:07.7511|INFO|Blockchain.BlockchainProcessor|Full Sync | Processed          4 |   24,472ms, mgasps    0.00 total    0.00, tps    0.12 total    0.07, bps    0.04 total    0.03, recv queue 0, proc queue 0
2020-03-13 09:48:07.8566|DEBUG|Network.Discovery.NodesLocator|Finished discovery cycle, tried contacting 0 nodes. All nodes count before the process: 0, after the process: 0
2020-03-13 09:48:07.8816|DEBUG|Network.Discovery.NodesLocator|Starting discovery process for node: masterNode: 0x38e72eeffc7be91834f7f16b7375b1978babf531eeeef5df74bba14bcf20d3b120935d07b1aae9785feaa2f8a7b849a8155b036eaeb03069ad015e7b9f30eb93
2020-03-13 09:48:08.0192|DEBUG|Consensus.AuRa.AuRaSealer|Skip seal block 5: 0x45dbc38c09eab8d1553667fe9d1bc4074450c7b3 is not proposer of AuRa step 1584092888.

2020-03-13 09:48:08.0214|DEBUG|Blockchain.Producers.BaseBlockProducer|Waiting 00:00:00.9800000 for next AuRa step.
2020-03-13 09:48:08.7475|DEBUG|Blockchain.Synchronization.Synchronizer|Allocating block sync.
2020-03-13 09:48:08.9880|DEBUG|Network.Discovery.NodesLocator|Finished discovery cycle, tried contacting 0 nodes. All nodes count before the process: 0, after the process: 0
2020-03-13 09:48:09.0099|DEBUG|Network.Discovery.NodesLocator|Starting discovery process for node: randomNode: 750e97...24b816
2020-03-13 09:48:09.0346|DEBUG|Consensus.AuRa.AuRaSealer|Skip seal block 5: 0x45dbc38c09eab8d1553667fe9d1bc4074450c7b3 is not proposer of AuRa step 1584092889.

2020-03-13 09:48:09.0405|DEBUG|Blockchain.Producers.BaseBlockProducer|Waiting 00:00:00.9600000 for next AuRa step.
2020-03-13 09:48:09.7497|DEBUG|Blockchain.Synchronization.Synchronizer|Allocating block sync.
2020-03-13 09:48:10.0162|DEBUG|Consensus.AuRa.AuRaSealer|Skip seal block 5: 0x45dbc38c09eab8d1553667fe9d1bc4074450c7b3 is not proposer of AuRa step 1584092890.
```

Nethermind client 2:
```2020-03-13 09:48:05.0156|DEBUG|Consensus.AuRa.AuRaSealer|Skip seal block 4: 0xa2e1a76d0d38a60038409835530cbafb524904d2 is not proposer of AuRa step 1584092885.

2020-03-13 09:48:05.0189|DEBUG|Blockchain.Producers.BaseBlockProducer|Waiting 00:00:00.9820000 for next AuRa step.
2020-03-13 09:48:05.1020|DEBUG|Network.Discovery.NodesLocator|Finished discovery cycle, tried contacting 0 nodes. All nodes count before the process: 0, after the process: 0
2020-03-13 09:48:05.1143|DEBUG|Network.Discovery.NodesLocator|Starting discovery process for node: randomNode: e586d2...4ac219
2020-03-13 09:48:05.5183|DEBUG|Blockchain.Synchronization.Synchronizer|Allocating block sync.
2020-03-13 09:48:06.0099|DEBUG|Consensus.AuRa.AuRaSealer|Skip seal block 4: 0xa2e1a76d0d38a60038409835530cbafb524904d2 is not proposer of AuRa step 1584092886.

2020-03-13 09:48:06.0109|DEBUG|Blockchain.Producers.BaseBlockProducer|Waiting 00:00:00.9900000 for next AuRa step.
2020-03-13 09:48:06.2639|DEBUG|Network.Discovery.NodesLocator|Finished discovery cycle, tried contacting 0 nodes. All nodes count before the process: 0, after the process: 0
2020-03-13 09:48:06.2816|DEBUG|Network.Discovery.NodesLocator|Starting discovery process for node: masterNode: 0xf96f97f47d411daabaf72d0d4c444b3704769f908b7f67b40e9af79c36566ea30a4ac054549a16ca9cb7e1be1805d8a19d871f60c2cd4ddb7056717ff5bb90dd
2020-03-13 09:48:06.5234|DEBUG|Blockchain.Synchronization.Synchronizer|Allocating block sync.
2020-03-13 09:48:07.0223|DEBUG|Consensus.AuRa.AuRaSealer|Skip seal block 4: 0xa2e1a76d0d38a60038409835530cbafb524904d2 is not proposer of AuRa step 1584092887.

2020-03-13 09:48:07.0321|DEBUG|Blockchain.Producers.BaseBlockProducer|Waiting 00:00:00.9750000 for next AuRa step.
2020-03-13 09:48:07.2958|INFO|Blockchain.Synchronization.SyncServer|Discovered a new block         4 09:48:07 (0xaa34c8...a32bbd), tx count: 3 sealed by 0x00bd138abd70e2f00903268f3db08f2d25677c9e, sent by 10.5.0.2:30300
2020-03-13 09:48:07.4098|DEBUG|Network.Discovery.NodesLocator|Finished discovery cycle, tried contacting 0 nodes. All nodes count before the process: 0, after the process: 0
2020-03-13 09:48:07.4098|DEBUG|Network.Discovery.NodesLocator|Starting discovery process for node: randomNode: 88a128...e31ba7
2020-03-13 09:48:07.5273|DEBUG|Blockchain.Synchronization.Synchronizer|Allocating block sync.
2020-03-13 09:48:07.5558|DEBUG|Consensus.AuRa.AuRaBlockFinalizationManager|Blocks finalized by 4 (0xaa34c8294e424c0fd51aef9e4ebed51b8a1ce893044d95e4cdc413bd90a32bbd): 4 (0xaa34c8294e424c0fd51aef9e4ebed51b8a1ce893044d95e4cdc413bd90a32bbd).
2020-03-13 09:48:07.5930|INFO|Blockchain.BlockchainProcessor|Full Sync | Processed          4 |   24,273ms, mgasps    0.00 total    0.00, tps    0.12 total    0.07, bps    0.04 total    0.02, recv queue 0, proc queue 0
2020-03-13 09:48:08.0167|DEBUG|Consensus.AuRa.AuRaSealer|Skip seal block 5: 0xa2e1a76d0d38a60038409835530cbafb524904d2 is not proposer of AuRa step 1584092888.

2020-03-13 09:48:08.0222|DEBUG|Blockchain.Producers.BaseBlockProducer|Waiting 00:00:00.9780000 for next AuRa step.
2020-03-13 09:48:08.5022|DEBUG|Network.Discovery.NodesLocator|Finished discovery cycle, tried contacting 0 nodes. All nodes count before the process: 0, after the process: 0
2020-03-13 09:48:08.5157|DEBUG|Network.Discovery.NodesLocator|Starting discovery process for node: masterNode: 0xf96f97f47d411daabaf72d0d4c444b3704769f908b7f67b40e9af79c36566ea30a4ac054549a16ca9cb7e1be1805d8a19d871f60c2cd4ddb7056717ff5bb90dd
2020-03-13 09:48:08.5284|DEBUG|Blockchain.Synchronization.Synchronizer|Allocating block sync.
2020-03-13 09:48:09.0212|DEBUG|Consensus.AuRa.AuRaSealer|Skip seal block 5: 0xa2e1a76d0d38a60038409835530cbafb524904d2 is not proposer of AuRa step 1584092889.

2020-03-13 09:48:09.0257|DEBUG|Blockchain.Producers.BaseBlockProducer|Waiting 00:00:00.9750000 for next AuRa step.
2020-03-13 09:48:09.5310|DEBUG|Blockchain.Synchronization.EthSyncPeerPool|Dropped 0 useless peers
2020-03-13 09:48:09.5323|DEBUG|Blockchain.Synchronization.Synchronizer|Allocating block sync.
2020-03-13 09:48:09.6653|DEBUG|Network.Discovery.NodesLocator|Finished discovery cycle, tried contacting 0 nodes. All nodes count before the process: 0, after the process: 0
2020-03-13 09:48:09.6683|DEBUG|Network.Discovery.NodesLocator|Starting discovery process for node: randomNode: ec6dc7...39c8d4
2020-03-13 09:48:10.0084|DEBUG|Consensus.AuRa.AuRaSealer|Skip seal block 5: 0xa2e1a76d0d38a60038409835530cbafb524904d2 is not proposer of AuRa step 1584092890.
```

**Code:**
For easy reproduction of the issue, I have attached the described docker project. Simply replace the volume paths in the docker-compose.yml file and use docker-compose up to start all nodes.
On some systems, parity has some trouble with writing privilege on first start. In that case restarting the parity client should resole the issue.

For sending transactions I used the following RPC command (also included in the readme):
`curl --data '{"jsonrpc":"2.0","method":"personal_sendTransaction","params":[{"from":"0x004ec07d2329997267ec62b4166639513386f32e","to":"0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e","value":"0xde0b6b3a7640000"}, "user"],"id":0}' -H "Content-Type: application/json" -X POST localhost:8545
`
[Nethermind_mining_issue.zip](https://github.com/NethermindEth/nethermind/files/4328960/Nethermind_mining_issue.zip)

**Comment by tkstanczak** [comment]
@moritz-mbw this will be picked up soon, also documentation for this is in progress

**Comment by tkstanczak** [comment]
fixed although we need to prepare tests for Nethermind + Parity

**Comment by jacekv** [comment]
The "fix" has not solved the problem. The problem is actually on how you write the validators into the genesis file. There is a difference between Parity and Nethermind. 

If you configure AuRa for Parity, the looks like this:
```
"engine": {
    "authorityRound": {
      "params": {
        "stepDuration": "30",
        "validators": {
          "list": [
            "0xAddress1",
            "0xAddress2",
            "0xAddress3"
          ]
        }
      }
    }
  }
```
For Nethermind it looks like that:
```
"engine": {
    "authorityRound": {
      "params": {
        "stepDuration": "30",
        "validators": {
          "multi": {
            "0": {
              "list": [
                "0xAddress1",
                "0xAddress2",
                "0xAddress3"
              ]
            }
          }
        }
      }
    }
  }
```
I actually realized the difference in one of your tutorials :)

**Comment by LukaszRozmej** [comment]
Hi, @jacekv , we do support same validators (multi, list, safecontract) as parity (we do not support reporting contract yet but this is coming soon). So the exact config you have for parity AuRa will work on Nethermind. I need to review our docs if it says it doesn't.

Also I will review if we can't mitigate the root issue better.

Sorry for all those delays and confusion, but I'm main person working on AuRa in Nethermind and currently am quite occupied with personal matters regarding coronavirus epidemic in Poland, hence the delays. @tkstanczak and @matilote wanted to unblock you as fast as possible and picked that up, but it created a bit of confusion.

**Comment by jacekv** [comment]
@LukaszRozmej The zip file provided by @moritz-mbw contains a genesis file, as described in the first example given. Nethermind works using this genesis file, but it won't seal blocks, giving the 
`... is not proper for AuRa step X`. Once I changed the genesis file, Nethermind started to seal blocks :)
